### ISSUE TITLE
Get start and end date on calendar items?

### ISSUE THREAD

**Issue by JustSteveKing** [spatie/laravel-google-calendar#15]
I am using the default Event::get() however i am unable to access the start and end properties for when an event starts and ends

**Comment by hugosp** [comment]
Same Here would be nice to get a complete Event-response

**Comment by Banandrew** [comment]
If I didn’t miss anything, [listEvents()](https://github.com/spatie/laravel-google-calendar/blob/master/src/GoogleCalendar.php#L39) returns a proper response with `start`/`end`, but they get lost when an array of events [becomes a collection](https://github.com/spatie/laravel-google-calendar/blob/master/src/Event.php#L115). I only needed to read a calendar, so I sort of forked that part of the package as a separate class, upgraded it to `"google/apiclient": "^2.0"`, and changed the collection transformation—if you have similar project goals and need an example, please let me know, I’ll put it up somewhere.

**Comment by freekmurze** [comment]
I'd accept a PR that adds this to the package.

**Comment by ttomdewit** [comment]
I've spent tonight trying to come up with a Pull Request to enable this functionality, and in the end all I got is that the `public` attributes are available when returning all events via `Event::get()`. Unfortunately, `modelData` (array) is `protected` and I think that's the reason it's currently not available from the Collection that is being returned.

I don't know how to make this work so I won't be looking into this any further. If anyone can point me in the right direction, I would gladly take another look.

Ping @Banandrew.

**Comment by ttomdewit** [comment]
I'd like to add that with the code I was able to access the `start` and `end` time of a dummy event I created.

```php
Route::get('/', function () {
    $events = Event::get();

    foreach ($events as $event) {
        dd($event->start);
    }
});
```

[Please see attached screenshot](https://www.dropbox.com/s/uidzgcatiimg3at/Screenshot%202017-01-19%2022.27.52.png?dl=0).

I do, however, think this should be returned from the Collection (when using `Event::get()` and available as a `Carbon` instance, for example.

**Comment by Banandrew** [comment]
@ttomdewit thanks for reminding me, you’re right; I dived into it tonight after your notification, but failed to find a solution that wasn’t messy.

@freekmurze I think it’s essential to return the `start` and the `end`, because that’s what it’s all about—would it be a stretch to say that most use-cases involve knowing when an event is going to start/end? The package does enough heavy lifting already, and while yes, it would be nice to get events as a Collection, I think the best solution would be for [Event::get()](https://github.com/spatie/laravel-google-calendar/blob/master/src/Event.php#L105) to return [listEvents()](https://github.com/spatie/laravel-google-calendar/blob/master/src/GoogleCalendar.php#L39) without making it a Collection, and let people choose the keys that they need. I don’t know, I just feel like writing ~10 very simple lines for a developer might be too much, considering the problem, what do you think?

**Comment by freekmurze** [comment]
I kinda like the fact that  `Event::get` returns a collection. You can access the underlying `Google_Service_Calendar_Event` class with

```php
$events = Event::get(...);
$event = $event->first();
$event-> googleEvent; //public property with the underlying `Google_Service_Calendar_Event`
```

However, I recognize the need for easily access the start- and endate. I'd accept a PR that adds methods to the `Event` class that return start- and endate as a `Carbon` instance.

**Comment by Banandrew** [comment]
@freekmurze I’ve figured it out. The `Event` class already has a getter set up with `__get`, so when you return `Event::get()` it uses [these mappings](https://github.com/spatie/laravel-google-calendar/blob/master/src/Event.php#L200) to return the start and the end dates as a `Carbon` instance. Everything works, and it’s just a documentation issue—I’ll submit a PR by Monday.
```PHP
// Pass Event::get() to a view as $events.

@foreach($events as $event)
    @if($event->startDate)
        <p>
            // getTimestamp() is a Carbon method:
            {{ $event->startDate->getTimestamp() }}
        </p>
    @endif
@endforeach
```
I feel like an idiot!

**Comment by freekmurze** [comment]
No need to feel like an idiot 😄 

I too overlooked those methods.

Looking forward to your PR that adds this to the readme.
