### ISSUE TITLE
Forbidden Issue

### ISSUE THREAD

**Issue by vrdvishwas** [spatie/laravel-google-calendar#64]
Hi,
I tried with same package and done all things as given steps.
But got the issue.
```
Google_Service_Exception
{
"error": {
"errors": [
{
"domain": "global",
"reason": "forbidden",
"message": "Forbidden"
}
],
"code": 403,
"message": "Forbidden"
}
}
```

**Comment by freekmurze** [comment]
Probably your problem is unrelated to this package, but something is off on how you configured things at Google. Try making an API request without this package first. When that succeeds try using this package. If you are unable to get the API request working, ask for help at the Google forums. 

If it turns out that there is indeed a problem with this package, reopen this PR.

Good luck!
