### ISSUE TITLE
How to Get Event with dynamic calendarId ?

### ISSUE THREAD

**Issue by baguskah** [spatie/laravel-google-calendar#76]
I want to get google Calendar event in multi calendar ID, how to do that ? thankyou before. This Package is very awesome, very like it

**Comment by baguskah** [comment]
just got the Solution in event.php =>>>> Event::find($eventId, $calendarId);
Thankyou

**Comment by noyruto5** [comment]
I have a similar problem. I used node js for google calendar api.
The problem is, how can I use multiple calendarId?

Here's the partial of my code:
```
var calendar = google.calendar('v3');
    calendar.events.list({
      auth: auth,
      calendarId: encodeURIComponent('en.philippines#holiday@group.v.calendar.google.com'),
      timeMin: (new Date()).toISOString(),
      maxResults: 1,
      singleEvents: true,
      orderBy: 'startTime',
    }, function(err, response) {

```

This is based from https://developers.google.com/google-apps/calendar/quickstart/nodejs.

And i tried:

calendarId: [encodeURIComponent('en.philippines#holiday@group.v.calendar.google.com'), encodeURIComponent('en-gb.japanese#holiday@group.v.calendar.google.com')],

**Comment by oakkapalazon** [comment]
I have multiple calendar in google. I want to use it depends on my projects. I cannot use
event.php =>>>> Event::find($eventId, $calendarId);
event.php =>>>> Event::create($properties, $calendarId);
but I can access Event::get($startDateTime, $endDateTime, $queryParameters, $calendarId);
